### ISSUE TITLE
[RFC] Include pre-commit install in git-aggregator (OCA context but not only)

### ISSUE THREAD

**Issue by legalsylvain** [acsone/git-aggregator#36]
Hi all,

git-aggregator is using ``git clone`` command to recover all the repository.
Since OCA is introducing pre-commit feature, I was thinking to automatically call the command ``pre-commit install`` after cloning a repository by git-aggregator. (we should check if pre-commit is installed / or add a new dependency).

(Ref : https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97)
Does it make sense for you ? 

kind regards.

**Comment by pedrobaeza** [comment]
For me not too much, as git aggregator is a deployment tool, not a development one.

**Comment by legalsylvain** [comment]
> For me not too much, as git aggregator is a deployment tool, not a development one.

thanks for your quick reply,  @pedrobaeza !

Well in fact, in OCA this tools is also used for development by some contributors. (at least at GRAP and at Akretion AFAIK). CC : @sebastienbeau ? 

So you're right, if introduced, this operation should be optional with an argument like ``gitaggregate -c repo --install-pre-commit`` and not enabled by default.

**Comment by pedrobaeza** [comment]
OK, let's see what others say

**Comment by lmignon** [comment]
@legalsylvain IMO git-aggregator is a generic tool and should remain the more generic as possible. I'm not in favor of adding a new layer of complexity to support something out of the  scope of aggregating branches...
Moreover, you can already implement this kind of functionality by defining [triggers](https://github.com/acsone/git-aggregator#triggers) into your configuration file.

**Comment by sbidoul** [comment]
In bash, would `gitaggregate -c repo.yml && pre-commit install` do the same?

**Comment by legalsylvain** [comment]
> In bash, would gitaggregate -c repo.yml && pre-commit install do the same?

I was more talking about each sub repo defined by the repo.ym. I think that the proposal of @lmignon covers my need. (manually, but it's ok).

something like that for each repository that belong pre-commit settings.

    .src/product_attribute:
        remotes:
        oca: https://github.com/OCA/product-attribute.git
        grap: https://github.com/grap/product-attribute.git
        merges:
            - oca 8.0
        target: grap aggregated_branch_name
        shell_command_after: pre-commit install

**Comment by legalsylvain** [comment]
Tested : Adding ``shell_command_after: pre-commit install`` in each repository meets my needs. 

Closing. Thanks @pedrobaeza, @sbidoul and @lmignon for your answers.
