### ISSUE TITLE
AGPL for a library?

### ISSUE THREAD

**Issue by Yajo** [acsone/git-aggregator#4]
This is more a question than an issue, although it could be an issue...

Why did you choose AGPL for a library? It is suited for web servers...

I'd have chosen GPL, whose section 13 makes it 100% compatible with AGPL, or LGPL.

Great tool, thanks!

**Comment by sbidoul** [comment]
@Yajo thanks for the feedback. Note it's more a stand-alone program than a library.

In practice what kind of potential issues do you see with AGPL in this case?

**Comment by Yajo** [comment]
It's just that the AGPL is "GPL for web applications", where the user is defined as the website visitor. Since this is a CLI library/program, it seems the license does not fit its purpose. GPL would be better in this case.

Please review:

- https://www.gnu.org/licenses/licenses.html#AGPL
- https://www.gnu.org/licenses/gpl-faq.html#AGPLv3InteractingRemotely
