### ISSUE TITLE
need restart after installing library

### ISSUE THREAD

**Issue by legalsylvain** [acsone/git-aggregator#44]
hi all,

I installed recently on new fresh computers (ubuntu 18.04) this library. via ``pip install git-aggregator``

Each time, I have to restart the system to have the ``gitaggregate`` command available.

do you have the same issue ?

does it come of pypi or from this library configuration ? 

thanks !

**Comment by sbidoul** [comment]
This looks like an issue with your shell. If using bash, try `which $(gitaggregate)`, and `rehash`.
Also always avoid running pip as root. Use `pip install --user`.

BTW, these days I recommend using [pipx](https://pypi.org/project/pipx/) for installing such python-based CLI tools.
