### ISSUE TITLE
using local cache

### ISSUE THREAD

**Issue by yelizariev** [acsone/git-aggregator#45]
I would like to suggest to add a new option, say ``--cache-dir`` and when it's presented use one of following options to initialise repository:

* use ``git clone --reference``
* use ``git worktree add`` command instead of ``git init`` -- looks as a better option as it doesn't require to change much in the scripts

This would decrease network and storage costs on working with big repositories like [odoo](https://github.com/odoo/odoo/)

**Comment by sbidoul** [comment]
Alternatively, if the first fetch was done with `git clone` instead of `git init + git fetch` it would naturally benefit from [git-autoshare](https://github.com/acsone/git-autoshare) if installed.

**Comment by sbidoul** [comment]
Possibly related to #28

**Comment by mileo** [comment]
> Alternatively, if the first fetch was done with `git clone` instead of `git init + git fetch` it would naturally benefit from [git-autoshare](https://github.com/acsone/git-autoshare) if installed.

Hi, @sbidoul I installed git-autoshare and git-aggregator, configure the PATH to use git autoshare automaticaly:

```
[mileo@mileo-xps odoo]$ git clone https://github.com/odoo/odoo src --branch=12.0 
git-autoshare clone added --reference /home/mileo/.cache/git-autoshare/github.com/odoo
Cloning into 'src'...
Updating files: 100% (22185/22185), done.
[mileo@mileo-xps odoo]$ 
```

But when i try to use git-aggregator it doesn't use the autoshare. Is there anything additional that must be done to integrate them?

**Comment by sbidoul** [comment]
@mileo that is what I was trying to explain [above](https://github.com/acsone/git-aggregator/issues/45#issuecomment-575210473). `git-aggregator` initializes the repo with `git init` + `git fetch`, so `git clone` is never called and therefore `git-autoshare` has no chance to kick in.

It might be possible to modifiy `git-aggregator` to do a `git clone` first.

**Comment by mileo** [comment]
> @mileo that is what I was trying to explain [above](https://github.com/acsone/git-aggregator/issues/45#issuecomment-575210473). `git-aggregator` initializes the repo with `git init` + `git fetch`, so `git clone` is never called and therefore `git-autoshare` has no chance to kick in.
> 
> It might be possible to modifiy `git-aggregator` to do a `git clone` first.

Ahh got it, in the end that's what i'm doing here. Thanks
