### ISSUE TITLE
aggregate option is optional in Python 3 but required in Python 2

### ISSUE THREAD

**Issue by Yajo** [acsone/git-aggregator#47]
This command works in python 3 but fails in python 2:

```bash
$ gitaggregate --expand-env --config repos.yaml --log-level INFO --jobs 2
usage: gitaggregate [-h] -c [CONFIG] [-p] [-d [DIRMATCH]]
                    [--log-level [LOG_LEVEL]] [-e] [--env-file ENV_FILE] [-f]
                    [-j JOBS]
                    {aggregate,show-all-prs,show-closed-prs} ...
gitaggregate: error: too few arguments
```

I have to append `aggregate` for py2 to work.

**Comment by ivantodorovich** [comment]
Yeap.. same here. It started requiring it a few days/weeks ago

**Comment by sbidoul** [comment]
Can't we drop python 2 support ?

Even if end-customer projects still need to support python 2, there should be no reason to use gitaggregator itself with python 2. I personally recommend to install-it in with pipx, outside of project environments.

**Comment by sbidoul** [comment]
We dropped python 2 support, so closing this.
