### ISSUE TITLE
Merge PR not working ?

### ISSUE THREAD

**Issue by ito-invest-js** [acsone/git-aggregator#61]
Hello,

I am trying this

./odoo:
  defaults:
    # Shallow repositories ($DEPTH_DEFAULT=1) are faster & thinner
    # You may need a bigger depth when merging PRs (use $DEPTH_MERGE
    # for a sane value of 100 commits)
    depth: $DEPTH_MERGE
  remotes:
    odoo: https://github.com/odoo/odoo.git
  target: odoo $ODOO_VERSION
  merges:
    - odoo $ODOO_VERSION
    - odoo refs/pull/80570/head

and it does not work, I got a 

fatal: refusing to merge unrelated histories

But this one is working,

./odoo:
  defaults:
    # Shallow repositories ($DEPTH_DEFAULT=1) are faster & thinner
    # You may need a bigger depth when merging PRs (use $DEPTH_MERGE
    # for a sane value of 100 commits)
    depth: $DEPTH_MERGE
  remotes:
    odoo: https://github.com/odoo/odoo.git
  target: odoo $ODOO_VERSION
  merges:
    - odoo $ODOO_VERSION
    # - odoo refs/pull/80570/head
    # Example of a merge of the PR with the number <PR>
    # - oca refs/pull/<PR>/head
  shell_command_after:
    - git fetch odoo 6d53dd12fbd4826f0d929e12e23119d5ac76e0a1 --depth 100
    - git cherry-pick 6d53dd12fbd4826f0d929e12e23119d5ac76e0a1 # refs/pull/80570/head

I could think it's related to fetching, but I cannot find a work around.

Thanks,

Jérôme

**Comment by legalsylvain** [comment]
Please try to set a bigger value to depth setting. It should fix the problem.

**Comment by ito-invest-js** [comment]
It solved it!! thanks alot.

**Comment by legalsylvain** [comment]
Could you close the issue ?
