### ISSUE TITLE
[RFC] new sub command "show-diff" or "show-status"

### ISSUE THREAD

**Issue by legalsylvain** [acsone/git-aggregator#63]
Hi all,

I use a lot git-aggregator locally, with a lot of repositories. Sometime I forgot a pending work in a repository, and before gitaggregate, i'd like to be sure all repo are "clean", and doens't have unadded / uncommited work.

For that purpose, I'd like to implement the following command 
``gitaggregate -c repos.yml show-status``

This command will scan each repository, and display the status (git status) of repos. (or something equivalent)

@sbidoul (+other git-aggregator developpers) : could you say me if this feature could be accepted in this project ? 

kind regards.

**Comment by sbidoul** [comment]
Would this not be solved by #37 ? ;)

Also `ls src | xargs -I {} git -C src/{} status`.

**Comment by legalsylvain** [comment]
Oh, I'm rambling ...
;-)
